version: "3"
services: 
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
    volumes:
      - ./db/initQueries.sql:/docker-entrypoint-initdb.d/initQueries.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: "exit 0"
    ports:
      - "3306:3306"

volumes:
  mysql_data: